[project]
name = "backpack-liquidation-limit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "backpack-exchange-sdk>=0.1.0",
    "colorlog>=6.9.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]
